name: Rust

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: rustup component add rustfmt

      - name: Install Pcap
        if: runner.os == 'Windows'
        run: |
               Invoke-WebRequest -UseBasicParsing https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -OutFile "${Env:TEMP}\wpd.zip"
               Expand-Archive -LiteralPath "${Env:TEMP}\wpd.zip" -DestinationPath "${Env:TEMP}\wpd"
               Move-Item -LiteralPath "${Env:TEMP}\wpd\WpdPack\Lib" -Destination lib

      - name: Format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Docs
        run: cargo doc --no-deps

